name: ${PROJECT_NAME}

services:
  web:
    container_name: ${APP_NAME}-web
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_DIR: build
    image: ${APP_NAME}:1.0
    ports:
      - "${HOST_PORT}:${CONTAINER_PORT}"
    environment:
      - NODE_ENV=${NODE_ENV}
      - APP_NAME=${APP_NAME}
    env_file:
      - ./.env
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ${LOG_VOLUME}:/var/log/nginx
    networks:
      - app-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:${CONTAINER_PORT}/ >/dev/null 2>&1 || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

  # Dev profil: ažuriranje bez novog image-a (čita ./build direktno)
  web-dev:
    profiles: ["dev"]
    container_name: ${APP_NAME}-dev
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./build:/usr/share/nginx/html:ro
      - ${LOG_VOLUME}:/var/log/nginx
    networks:
      - app-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:80/ >/dev/null 2>&1 || exit 1"]

networks:
  app-net:

volumes:
  nginxlogs:

